// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SpaceCare.Infra.Data;

#nullable disable

namespace SpaceCare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602125323_CriarTabelaTelemetrias")]
    partial class CriarTabelaTelemetrias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceCare.Domain.Telemetrias.Telemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatimentosCardiacos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BATIMENTOS");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<string>("PressaoArterial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PRESSAO_ARTERIAL");

                    b.Property<decimal>("TemperaturaCorporal")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("TEMPERATURA");

                    b.Property<int>("TuristaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TURISTA_ID");

                    b.HasKey("Id");

                    b.HasIndex("TuristaId");

                    b.ToTable("SC_TELEMETRIAS", (string)null);
                });

            modelBuilder.Entity("SpaceCare.Domain.Turistas.Turista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(1)")
                        .HasDefaultValue("1")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("HistoricoMedico")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("HISTORICO_MEDICO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("PassaporteEspacial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_PASSAPORTE_ESPACIAL");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PassaporteEspacial")
                        .IsUnique();

                    b.ToTable("SC_TURISTAS");
                });

            modelBuilder.Entity("SpaceCare.Domain.Telemetrias.Telemetria", b =>
                {
                    b.HasOne("SpaceCare.Domain.Turistas.Turista", "Turista")
                        .WithMany()
                        .HasForeignKey("TuristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turista");
                });
#pragma warning restore 612, 618
        }
    }
}
